language: dart

dart:
  - dev
  # Uncomment after stable 2.0 is published
  #- stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script: ./build.sh

branches:
  only:
    - master
    - dart2
