name: mustache4dart
version: 2.1.0
author: Georgios Valotasios <valotas@gmail.com>
description: A mustache implementation for the Dart language
homepage: https://github.com/valotas/mustache4dart
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
