name: mustache4dart
version: 0.0.13+0.5.3.0
author: Georgios Valotasios <valotas@gmail.com>
description: A mustache implementation for the Dart language
homepage: https://github.com/valotas/mustache4dart
dependencies:
  unittest: '>=0.5.0'

#  js: any