name: mustache4dart
version: 0.0.11+0.4.7.1
author: Georgios Valotasios <valotas@gmail.com>
description: A mustache implementation for the Dart language
homepage: https://github.com/valotas/mustache4dart
dependencies:
  unittest: '>=0.4.2 <0.5.0'

#  js: any