name: mustache4dart
version: 3.0.0-dev.1.0
author: Georgios Valotasios <valotas@gmail.com>
description: A mustache implementation for the Dart language
homepage: https://github.com/valotas/mustache4dart
environment:
  sdk: '>=2.0.0-dev.64.1 <3.0.0'
dependencies:
  reflectable: ^2.0.4
dev_dependencies:
  test: ^1.3.0
  isolate: ^2.0.0
  build_runner: any
  build_test: any
  # build_web_compilers: ^0.4.0